
//-----------------------------------------------------------------------
// * Copyright (C) 2018 UU898 Enterprises All Rights Reserved
// * author  : auto generated by ModelGenerator
//-----------------------------------------------------------------------
using System;
using Loogn.OrmLite;

namespace project.model.entity
{
    /// <summary>
    /// 系统用户角色
    /// </summary>
    public partial class SystemUser_Role
    {
        /// <summary>
        /// 
        /// </summary>
        [OrmLiteField(IsPrimaryKey = true, InsertIgnore = true)]
        public long Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public long SystemUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public long SystemRoleId { get; set; }
    }
}