
//-----------------------------------------------------------------------
// * Copyright (C) 2018 UU898 Enterprises All Rights Reserved
// * author  : auto generated by ModelGenerator
//-----------------------------------------------------------------------
using System;
using Loogn.OrmLite;

namespace project.model.entity
{
    /// <summary>
    /// 员工表
    /// </summary>
    public partial class SystemUser
    {
        /// <summary>
        /// 
        /// </summary>
        [OrmLiteField(IsPrimaryKey = true, InsertIgnore = true)]
        public long Id { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        public string Username { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 昵称
        /// </summary>
        public string Nickname { get; set; }
        /// <summary>
        /// 1-男，2-女
        /// </summary>
        public byte Gender { get; set; }
        /// <summary>
        /// 状态，1-正常，2-禁用
        /// </summary>
        public byte Status { get; set; }
        /// <summary>
        /// 头像
        /// </summary>
        public string Avatar { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        public DateTime AddTime { get; set; }
    }
}