
//-----------------------------------------------------------------------
// * Copyright (C) 2018 UU898 Enterprises All Rights Reserved
// * author  : auto generated by ModelGenerator
//-----------------------------------------------------------------------
using System;
using Loogn.OrmLite;

namespace project.model
{
    /// <summary>
    /// 计数限制
    /// </summary>
    public class CountLimit
    {
        [OrmLiteField(IsPrimaryKey = true, InsertIgnore = true)]
        public long Id { get; set; }
        /// <summary>
        /// 唯一标识
        /// </summary>
        public string UniqueId { get; set; }
        /// <summary>
        /// 已有计数
        /// </summary>
        public int AlreadyCount { get; set; }
        /// <summary>
        /// 开始计数时间
        /// </summary>
        public DateTime BeginTime { get; set; }
    }
}