
//-----------------------------------------------------------------------
// * Copyright (C) 2018 UU898 Enterprises All Rights Reserved
// * author  : auto generated by ModelGenerator
//-----------------------------------------------------------------------

using Loogn.OrmLite;

namespace project.dao.Models
{
    /// <summary>
    /// 系统用户资源
    /// </summary>
    public partial class SystemUser_Res
    {
        /// <summary>
        /// 
        /// </summary>
        [OrmLiteField(IsPrimaryKey = true, InsertIgnore = true)]
        public long Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public long SystemUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public long SystemResId { get; set; }
    }
}